"""
=========================================================
NOONGIL-X Layer 4
Utility: JSON Writer
=========================================================

Purpose:
---------
Safely save JSON outputs generated by the
Cognitive Reasoning Layer.

Used By:
--------
- context_analyzer.py
- cognitive_state_manager.py
- situation_understanding.py
- intent_reasoner.py
- prediction_engine.py
- hazard_reasoner.py
- reasoning_fusion.py
- decision_engine.py
- explanation_engine.py

=========================================================
"""

import json

from pathlib import Path


# =========================================================
# SAVE JSON
# =========================================================

def save_json(
        data,
        output_file
):

    output_file = Path(output_file)

    print("\n" + "-" * 60)
    print(f"[INFO] Saving JSON")
    print(f"[INFO] Output: {output_file}")
    print("-" * 60)

    try:

        # --------------------------------------------
        # CREATE DIRECTORY IF MISSING
        # --------------------------------------------

        output_file.parent.mkdir(

            parents=True,

            exist_ok=True
        )

        # --------------------------------------------
        # SAVE FILE
        # --------------------------------------------

        with open(
                output_file,
                "w",
                encoding="utf-8"
        ) as file:

            json.dump(

                data,

                file,

                indent=4,

                ensure_ascii=False
            )

        print("[SUCCESS] JSON Saved")

        if isinstance(data, dict):

            print(
                f"[DEBUG] Keys: "
                f"{list(data.keys())}"
            )

        elif isinstance(data, list):

            print(
                f"[DEBUG] Items: "
                f"{len(data)}"
            )

        print(
            f"[DEBUG] File Size: "
            f"{output_file.stat().st_size} bytes"
        )

        return True

    except Exception as e:

        print("[ERROR] Failed To Save JSON")
        print(f"[DEBUG] {e}")

        return False


# =========================================================
# APPEND TO JSON LIST
# =========================================================

def append_json_list(
        item,
        output_file
):

    output_file = Path(output_file)

    print("\n" + "-" * 60)
    print("[INFO] Appending To JSON List")
    print("-" * 60)

    try:

        if output_file.exists():

            with open(
                    output_file,
                    "r",
                    encoding="utf-8"
            ) as file:

                data = json.load(file)

        else:

            data = []

        if not isinstance(data, list):

            print(
                "[ERROR] Target File "
                "Does Not Contain List"
            )

            return False

        data.append(item)

        save_json(
            data,
            output_file
        )

        print("[SUCCESS] Item Appended")

        return True

    except Exception as e:

        print("[ERROR] Append Failed")
        print(f"[DEBUG] {e}")

        return False


# =========================================================
# OVERWRITE CHECK
# =========================================================

def file_exists(
        output_file
):

    output_file = Path(output_file)

    exists = output_file.exists()

    print(
        f"[DEBUG] Exists: "
        f"{exists}"
    )

    return exists


# =========================================================
# TEST
# =========================================================

if __name__ == "__main__":

    print("\n" + "=" * 60)
    print("NOONGIL-X JSON WRITER TEST")
    print("=" * 60)

    test_data = {

        "module":
        "json_writer",

        "status":
        "working"
    }

    test_file = (

        Path(__file__).resolve()

        .parent.parent

        / "output"

        / "json_writer_test.json"
    )

    save_json(

        test_data,

        test_file
    )

    print(
        "\n[SUCCESS] json_writer.py "
        "is working correctly"
    )